[versions]
agp = "8.7.1"
bom = "3.0.1"
githubBom = "3.0.1"  # Sostituisci con la versione corretta
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
ktorClientCore = "3.0.0"
ktorClientOkhttp = "2.0.0"
lifecycleRuntimeKtx = "2.8.6"
activityCompose = "1.9.3"
composeBom = "2024.10.00"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
auth-kt = { module = "io.github.jan-tennert.supabase:auth-kt" }
github-auth-kt = { module = "io.github.jan-tennert.supabase:auth-kt" }
github-bom = { module = "io.github.jan-tennert.supabase:bom", version = "3.0.1" }
github-postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt" }
github-realtime-kt = { module = "io.github.jan-tennert.supabase:realtime-kt" }
io-github-jan-tennert-supabase-auth-kt = { module = "io.github.jan-tennert.supabase:auth-kt" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt" }
realtime-kt = { module = "io.github.jan-tennert.supabase:realtime-kt" }
gotrue-kt = { module = "io.github.jan-tennert.supabase:gotrue-kt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClientOkhttp" }
supabase-auth-kt = { module = "io.github.jan-tennert.supabase:auth-kt" }
supabase-postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt", version = "3.0.1" }
supabase-realtime-kt = { module = "io.github.jan-tennert.supabase:realtime-kt", version = "3.0.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }  # Corretto qui